Repository prgrms-web-devcourse/Team-03-LinkBook-FE, pull requests merged in 2022-08, with the labels that each got.

#37 Feat: 북마크 리스트 및 아이템 구현
  web/components/BookmarkItem/BookmarkItem.style.ts
  web/components/BookmarkItem/BookmarkItem.tsx
  web/components/BookmarkItem/index.ts
  web/components/BookmarkList/BookmarkList.style.ts
  web/components/BookmarkList/BookmarkList.tsx
  web/components/BookmarkList/index.ts
  web/components/index.ts
  web/hooks/useCopyUrl.ts
  web/public/icons/clip.svg
  web/public/icons/delete.svg
  web/public/icons/pencil.svg
  web/public/icons/star.svg
Labels: feat, 보통

#43 Feat: ImageUpload 컴포넌트 구현
  web/components/ImageUpload/ImageUpload.style.ts
  web/components/ImageUpload/ImageUpload.tsx
  web/components/ImageUpload/ModalPreview/ModalPreview.style.ts
  web/components/ImageUpload/ModalPreview/ModalPreview.tsx
  web/components/ImageUpload/ModalPreview/index.ts
  web/components/ImageUpload/PagePreview/PagePreview.style.ts
  web/components/ImageUpload/PagePreview/PagePreview.tsx
  web/components/ImageUpload/PagePreview/index.ts
  web/components/ImageUpload/index.ts
  web/components/index.ts
Labels: feat, 보통

#50 Feat: Tag 컴포넌트 Shrink 추가
  web/components/Card/Card.tsx
  web/components/Category/Category.tsx
  web/components/Tag/Tag.tsx
  web/components/Tag/TagItem/TagItem.style.ts
  web/components/Tag/TagItem/TagItem.tsx
  web/pages/index.tsx
Labels: feat

#41 Feat: Pagination 컴포넌트 구현, folderList 페이지 UI 구현
  web/components/Card/Card.tsx
  web/components/Category/Category.style.ts
  web/components/Category/Category.tsx
  web/components/Category/index.ts
  web/components/Pagination/Pagination.style.ts
  web/components/Pagination/Pagination.tsx
  web/components/Pagination/index.ts
  web/components/Tab/Tab.tsx
  web/components/Tag/Tag.tsx
  web/components/Tag/TagItem/TagItem.style.ts
  web/components/Tag/TagItem/TagItem.tsx
  web/components/index.ts
  web/pages/components/Category/Category.tsx
  web/pages/components/MainCategory/MainCategory.style.ts
  web/pages/components/MainCategory/MainCategory.tsx
  web/pages/components/MainCategory/index.ts
  web/pages/components/index.ts
  web/pages/folderlist/components/SerachBar/SearchBar.style.ts
  web/pages/folderlist/components/SerachBar/SerachBar.tsx
  web/pages/folderlist/components/SerachBar/index.ts
  web/pages/folderlist/index.style.ts
  web/pages/folderlist/index.tsx
  web/shared/DummyData.ts
  web/shared/DummyDataType.ts
  web/shared/categoryCardDummy.ts
  web/shared/folderListPageDummy.ts
Labels: refactor, feat, 보통

#58 Feat: 404 페이지 구현(초안)
  web/pages/404.tsx
  web/pages/index.style.ts
Labels: feat, 긴급

#61 Feat : comment input Component version 추가
  web/components/Card/Card.style.ts
  web/components/Comment/Comment.tsx
  web/components/CommentInput/CommentInput.tsx
  web/components/Modal/Modal.style.ts
  web/components/NavigationBar/NavigationBar.tsx
  web/pages/folderdetail/components/CommentSection/CommentList/CommentList.tsx
  web/pages/folderdetail/components/CommentSection/CommentSection.style.ts
  web/pages/folderdetail/components/CommentSection/CommentSection.tsx
  web/pages/folderdetail/components/ContentSection/ContentSection.style.ts
  web/pages/folderdetail/components/ContentSection/ContentSection.tsx
  web/pages/folderupdate/[id].tsx
Labels: 리뷰 요청, feat, 긴급

#68 Feat: Layout 컴포넌트 추가, _app.tsx 변경
  web/components/Layout.tsx
  web/pages/_app.tsx
Labels: feat

#77 Chore: 컴포넌트 디렉토리 경로 수정
  web/next.config.js
  web/pageComponents/folderdetailComponents/components/CommentSection/CommentList/CommentList.style.ts
  web/pageComponents/folderdetailComponents/components/CommentSection/CommentList/CommentList.tsx
  web/pageComponents/folderdetailComponents/components/CommentSection/CommentList/index.ts
  web/pageComponents/folderdetailComponents/components/CommentSection/CommentSection.style.ts
  web/pageComponents/folderdetailComponents/components/CommentSection/CommentSection.tsx
  web/pageComponents/folderdetailComponents/components/CommentSection/index.ts
  web/pageComponents/folderdetailComponents/components/ContentSection/ContentSection.style.ts
  web/pageComponents/folderdetailComponents/components/ContentSection/ContentSection.tsx
  web/pageComponents/folderdetailComponents/components/ContentSection/index.ts
  web/pageComponents/folderdetailComponents/components/index.ts
  web/pageComponents/folderlistComponents/components/SearchBar/SearchBar.style.ts
  web/pageComponents/folderlistComponents/components/SearchBar/SearchBar.tsx
  web/pageComponents/folderlistComponents/components/SearchBar/index.ts
  web/pageComponents/folderupdateComponents/components/Switch/Switch.style.ts
  web/pageComponents/folderupdateComponents/components/Switch/Switch.tsx
  web/pageComponents/folderupdateComponents/components/Switch/index.ts
  web/pageComponents/folderupdateComponents/components/index.ts
  web/pageComponents/mainPageComponents/components/FolderSlider/FolderSlider.style.ts
  web/pageComponents/mainPageComponents/components/FolderSlider/FolderSlider.tsx
  web/pageComponents/mainPageComponents/components/FolderSlider/index.ts
  web/pageComponents/mainPageComponents/components/MainCategory/MainCategory.style.ts
  web/pageComponents/mainPageComponents/components/MainCategory/MainCategory.tsx
  web/pageComponents/mainPageComponents/components/MainCategory/index.ts
  web/pageComponents/mainPageComponents/components/MyFoldersAreaLogIn/MyFoldersAreaLogIn.style.ts
  web/pageComponents/mainPageComponents/components/MyFoldersAreaLogIn/MyFoldersAreaLogIn.tsx
  web/pageComponents/mainPageComponents/components/MyFoldersAreaLogIn/data.js
  web/pageComponents/mainPageComponents/components/MyFoldersAreaLogIn/index.ts
  web/pageComponents/mainPageComponents/components/MyFoldersAreaLogOut/MyFoldersAreaLogOut.style.ts
  web/pageComponents/mainPageComponents/components/MyFoldersAreaLogOut/MyFoldersAreaLogOut.tsx
  web/pageComponents/mainPageComponents/components/MyFoldersAreaLogOut/index.ts
  web/pageComponents/mainPageComponents/components/UseInfo/UseInfo.style.ts
  web/pageComponents/mainPageComponents/components/UseInfo/UseInfo.tsx
  web/pageComponents/mainPageComponents/components/UseInfo/index.ts
  web/pageComponents/mainPageComponents/components/index.ts
  web/pages/404.tsx
  web/pages/folderdetail/[id].tsx
  web/pages/folderlist/index.tsx
  web/pages/folderupdate/[id].tsx
  web/pages/index.tsx
  web/pages/information/index.tsx
  web/pages/user/[id].tsx
  web/styles/pageStyles/folderDetail.style.ts
  web/styles/pageStyles/folderList.style.ts
  web/styles/pageStyles/folderUpdate.style.ts
  web/styles/pageStyles/index.style.ts
  web/styles/pageStyles/information.style.ts
  web/styles/pageStyles/user.style.ts
Labels: chore

#91 Feat : login Modal 로직 구현
  web/apis/UserAPI.ts
  web/components/Modal/Login/Login.tsx
  web/components/Modal/Modal.style.ts
  web/components/Modal/Modal.tsx
  web/components/Modal/SignUp/SignUp.tsx
  web/components/Modal/SignUp/SignUpPage/Page01.tsx
  web/components/Modal/SignUp/SignUpPage/Page02.tsx
  web/components/Modal/SignUp/contexts/UserProvider.tsx
  web/components/NavigationBar/NavigationBar.tsx
  web/types/user.ts
Labels: 리뷰 요청, feat, 보통

#94 Fix: Git 충돌 해결
  web/apis/UserAPI.ts
  web/components/Modal/Login/Login.tsx
  web/components/Modal/SignUp/SignUpPage/Page02.tsx
  web/components/Modal/SignUp/contexts/UserProvider.tsx
Labels: 긴급, fix

#95 Feat: 모달 Login 초안 작성 및 FolderModal02 추가
  extension/src/App.tsx
  extension/src/components/Modal/Modal.tsx
  extension/src/components/Modal/SelectFolder/FolderModal02.tsx
  extension/src/pages/Login.tsx
  extension/src/pages/MainPage.tsx
  extension/src/pages/RootStack.tsx
Labels: 보통

#105 Feat: folder update api
  web/.gitignore
  web/apis/FolderAPI.ts
  web/components/BookmarkItem/BookmarkItem.tsx
  web/components/BookmarkList/BookmarkList.tsx
  web/components/ImageUpload/ImageUpload.tsx
  web/next.config.js
  web/package-lock.json
  web/package.json
  web/pageComponents/folderupdateComponents/components/BookmarkInput/BookmarkInput.style.ts
  web/pageComponents/folderupdateComponents/components/BookmarkInput/BookmarkInput.tsx
  web/pageComponents/folderupdateComponents/components/BookmarkInput/index.ts
  web/pageComponents/folderupdateComponents/components/Switch/Switch.tsx
  web/pageComponents/folderupdateComponents/components/index.ts
  web/pages/folderupdate/[id].tsx
  web/styles/pageStyles/folderUpdate.style.ts
  web/types/bookmark.ts
  web/types/folder.ts
  web/types/index.ts
  web/util/S3ImageHandler.ts
Labels: feat, 긴급

#108 Feat: signUp 로직
  web/apis/EmailAPI.ts
  web/apis/UserAPI.ts
  web/apis/url.ts
  web/components/Input/Input.style.ts
  web/components/Input/Input.tsx
  web/components/Modal/Login/Login.tsx
  web/components/Modal/Modal.style.ts
  web/components/Modal/Modal.tsx
  web/components/Modal/SignUp/SignUpPage/Page01.tsx
  web/components/Modal/SignUp/SignUpPage/Page02.tsx
  web/components/Modal/SignUp/contexts/UserProvider.tsx
  web/components/NavigationBar/HandleModalSection/HandleModalSection.tsx
  web/components/NavigationBar/HandleModalSection/index.ts
  web/components/NavigationBar/LoginSection/LoginSection.tsx
  web/components/NavigationBar/LoginSection/index.ts
  web/components/NavigationBar/LogoutSection/LogoutSection.tsx
  web/components/NavigationBar/LogoutSection/index.ts
  web/components/NavigationBar/NavigationBar.tsx
  web/constants/modal.constants.ts
  web/constants/regex.constants.ts
  web/constants/validation.constants.ts
  web/pageComponents/mainPageComponents/components/MyFoldersAreaLogOut/MyFoldersAreaLogOut.tsx
  web/pages/folderupdate/[id].tsx
  web/pages/user/[id].tsx
  web/recoil/authentication.tsx
  web/recoil/showModal.tsx
Labels: 리뷰 요청, feat, 보통

#123 Feat: first login modal 로직 구현 + Comment 로직 수정
  web/apis/UserAPI.ts
  web/components/Comment/Comment.tsx
  web/components/Comment/CommentItem/CommentItem.tsx
  web/components/CommentInput/CommentInput.tsx
  web/components/Modal/FirstLogin/FirstLogin.tsx
  web/components/Modal/FirstLogin/FirstLoginPage/Page01.tsx
  web/components/Modal/FirstLogin/FirstLoginPage/Page02.tsx
  web/components/Modal/FirstLogin/FirstLoginPage/Page03.tsx
  web/components/Modal/FirstLogin/FirstLoginPage/Page04.tsx
  web/components/Modal/FirstLogin/FirstLoginPage/Page05.tsx
  web/components/Modal/FirstLogin/contexts/UserInfoProvider.tsx
  web/components/Modal/Login/Login.tsx
  web/components/Modal/Modal.style.ts
  web/components/Modal/SignUp/SignUpPage/Page01.tsx
  web/components/Modal/SignUp/SignUpPage/Page02.tsx
  web/components/NavigationBar/LoginSection/LoginSection.tsx
  web/components/NavigationBar/NavigationBar.style.ts
  web/components/NavigationBar/NavigationBar.tsx
  web/components/TagSelector/TagSelector.tsx
  web/constants/alert.constants.ts
  web/pageComponents/folderdetailComponents/components/ContentSection/ContentSection.tsx
  web/pageComponents/folderdetailComponents/components/LikeButtonSection/LikeButtonSection.tsx
  web/pageComponents/folderdetailComponents/components/PrivateSection/PrivateSection.tsx
  web/pageComponents/folderdetailComponents/components/ScrapButtonSection/ScrapButtonSection.tsx
  web/pages/folderdetail/[id].tsx
  web/recoil/user.tsx
  web/types/user.ts
Labels: 리뷰 요청, feat, 긴급

#158 버그 해결 Deploy
  README.md
  extension/.gitignore
  extension/build/asset-manifest.json
  extension/build/favicon.ico
  extension/build/icons/btn_x.png
  extension/build/icons/defaultImg.png
  extension/build/icons/logo-128.png
  extension/build/icons/logo-16.png
  extension/build/icons/logo-48.png
  extension/build/icons/logo-ex.png
  extension/build/icons/logo.png
  extension/build/index.html
  extension/build/manifest.json
  extension/build/robots.txt
  extension/build/static/js/content.js
  extension/build/static/js/main.js
  extension/build/static/js/main.js.LICENSE.txt
  extension/build/static/js/main.js.map
  extension/src/pages/LoginPage/LoginPage.tsx
  extension/src/utils/api.ts
  extension/src/utils/constants.ts
  extension/src/utils/cookies.ts
  web/pages/information/index.tsx
Labels: fix, deploy
