Repository prgrms-web-devcourse/Team-03-LinkBook-FE, pull requests merged in 2022-07, with the labels that each got.

#2 feat: globalCss, theme 설정 및 eslint rule 추가
  web/.eslintrc.js
  web/.eslintrc.json
  web/.storybook/preview.js
  web/@types/import-emotion.d.ts
  web/package-lock.json
  web/package.json
  web/pages/_app.tsx
  web/pages/api/hello.ts
  web/pages/index.style.ts
  web/pages/index.tsx
  web/stories/Button.stories.tsx
  web/stories/Button.tsx
  web/stories/button.css
  web/styles/GlobalStyle.tsx
  web/styles/Home.module.css
  web/styles/globals.css
  web/styles/themes.ts
  web/tsconfig.json
  web/yarn.lock
Labels: feat, 보통

#6 Chore: theme color, fontSize 변수 추가
  web/@types/import-emotion.d.ts
  web/next.config.js
  web/styles/themes.ts
Labels: 보통, chore

#7 Chore: react-query 추가
  web/package-lock.json
  web/package.json
Labels: chore

#16 Feat: Avatar, Icon 컴포넌트 구현
  web/components/Avatar/Avatar.style.ts
  web/components/Avatar/Avatar.tsx
  web/components/Avatar/index.ts
  web/components/Icon/Icon.tsx
  web/components/Icon/index.ts
  web/components/index.ts
  web/public/icons/arrowLeft.svg
  web/public/icons/arrowRight.svg
  web/public/icons/bookmark.svg
  web/public/icons/camera.svg
  web/public/icons/comment.svg
  web/public/icons/commentWhite.svg
  web/public/icons/likesFill.svg
  web/public/icons/likesLine.svg
  web/public/icons/more.svg
  web/public/icons/userLine.svg
  web/public/icons/x.svg
Labels: feat, 보통

#15 Feat: footer 컴포넌트 구현
  web/components/Footer/Footer.stories.tsx
  web/components/Footer/Footer.style.ts
  web/components/Footer/Footer.tsx
  web/components/Footer/FooterItem/FooterItem.style.ts
  web/components/Footer/FooterItem/FooterItem.tsx
  web/components/Footer/FooterItem/index.ts
  web/components/Footer/SNSButton/SNSButton.style.ts
  web/components/Footer/SNSButton/SNSButton.tsx
  web/components/Footer/SNSButton/index.ts
  web/components/Footer/index.ts
  web/components/index.ts
  web/pages/_app.tsx
Labels: 리뷰 요청, feat, 보통

#21 Feat: tag 컴포넌트, tab 컴포넌트 구현
  web/components/Tab/Tab.style.ts
  web/components/Tab/Tab.tsx
  web/components/Tab/TabItem/TabItem.style.ts
  web/components/Tab/TabItem/TabItem.tsx
  web/components/Tab/TabItem/index.ts
  web/components/Tab/index.ts
  web/components/Tag/Tag.style.ts
  web/components/Tag/Tag.tsx
  web/components/Tag/TagItem/TagItem.style.ts
  web/components/Tag/TagItem/TagItem.tsx
  web/components/Tag/TagItem/index.tsx
  web/components/Tag/index.ts
  web/components/index.ts
Labels: feat

#27 Design: Footer SNSButton Logo 추가
  web/components/Footer/Footer.style.ts
  web/components/Footer/Footer.tsx
  web/components/Footer/SNSButton/SNSButton.style.ts
  web/components/Footer/SNSButton/SNSButton.tsx
  web/public/icons/ico_instagram.svg
  web/public/icons/ico_kakaochannel.svg
Labels: 리뷰 요청, style

#34 Feat: DummyData 생성
  web/next.config.js
  web/shared/DummyData.ts
  web/shared/DummyDataType.ts
  web/shared/common.ts
Labels: feat, 긴급

#28 24/feat/category 컴포넌트 구현
  web/components/Skeleton/Skeleton.stories.tsx
  web/components/Skeleton/Skeleton.style.ts
  web/components/Skeleton/Skeleton.tsx
  web/components/Skeleton/index.ts
  web/components/index.ts
  web/pages/components/Category/Category.style.ts
  web/pages/components/Category/Category.tsx
  web/pages/components/Category/index.ts
  web/pages/components/index.ts
  web/public/icons/search_ic.svg
  web/shared/categoryCardDummy.ts
  web/styles/themes.ts
Labels: feat
